### ISSUE TITLE
Infinite XP from ores that drop themselves

### ISSUE THREAD

**Issue by wolfpaw682** [MikeTheShadow/VoluminousEnergy#10]
For all of the ores that drop an ore block when broken, xp is granted to the player. These blocks can be placed back down and mined again for more xp. In the case of vanilla ores that behave like this like iron and gold, xp is not granted when the block is mined but when it is smelted.

**Comment by Eelt** [comment]
This is true, the quick and easy fix for this would be to enable/disable XP drop of ores in the config.

A more long term fix for this issue would be to figure out how to store NBT data (I'm theorizing here) to determine if it's natural or has been mined (could be a simple boolean). The thing is, I don't want to turn every single ore in Voluminous Energy into a Tile Entity to achieve this.

Though I would add that in the past (probably present as well) there are tools/tool upgrades that would add XP drops to all blocks (think copper in Tinkers'), so balancing the amount of XP should also be a consideration.

Making the TEs drop XP for some of the ores like Bauxite, Rutile, and Galena I can see as an option, but since the next upcoming release is coming up really soon, I don't feel like reworking them just yet to handle this right now.

**Comment by Eelt** [comment]
Okay, so adding XP drops to the Item Handler is not that bad after checking out the Abstract Furnace Tile. This also allowed me to fix the Gas Fired Furnace and the Electric Furnace so that it drops XP like the vanilla furnace.
