### ISSUE TITLE
Any liquids from Voluminous Energy turn into air

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [MikeTheShadow/VoluminousEnergy#11]
Hello! Recently found your mod and played a bit with it, it was fun to play (if it's not abandoned, it can be really one of the interesting mods to play as well). After playing some time I noticed big crude oil geysers that is striking through all the way from bedrock to clouds... but when I try to swim in them: I'm just felt through oil and fallen on bedrock with lots of damage. So oil have no liquid physics and basically is air.

You can see the screenshot below to see a problem with **any fluid** in the mod. Using version from CurseForge (which is 1.16.3+-0.0.0.1), but I see that there were a lot of commits in 1.16.3 branch, if it fixed in dev, feel free to close this issue.
![image](https://user-images.githubusercontent.com/27882185/107257906-fd0daf00-6a5c-11eb-8705-38c16c95b1e1.png)

**Forge version**: 35.1.37
**Minecraft version**: 1.16.4 (but moving to 1.16.5 doesn't solve this)
**Voluminous Energy version**: VoluminousEnergy-1.16.3+-0.0.0.1
If you need more info or logs, feel free to ask them.

**Comment by Eelt** [comment]
Hi, 

Currently, fluids are very limited in newer versions of Forge (1.13+) which is why there is no physics for any Voluminous Energy fluids. I believe most other mods that add fluids in 1.13+ versions of forge, unless they write their own implementations of fluids have this same issue. So, the lack of physics for fluids will not be fixed anytime soon.

A new release with a bunch of bug fixes and enhancements should be coming out soon (probably later this month).

**Comment by Eelt** [comment]
I managed to do something about this. We'll see in the next update if it's any good or not.
