### ISSUE TITLE
Data Pack issues.

### ISSUE THREAD

**Issue by border999** [MikeTheShadow/VoluminousEnergy#111]
**Describe the bug**
Adding this mod to my modpack makes it impossible to join any worlds I have previously made or to get into ones I create after it is installed. All worlds in question point to some form of data pack issue being the reason.

**Expected behavior**
To be able to join or create a world without issue.

**Logs**
https://gist.github.com/border999/8957857df3ff8bd09d37602f59a29a05
https://gist.github.com/border999/f46ce307cfa52248b236d4b2b00aab3f

**Desktop (please complete the following information):**
- OS Windows
- Mod Version VoluminousEnergy-1.18.2JX-0.4+Alpha+2
- Forge Version 40.2.0

**Comment by Eelt** [comment]
There are obviously API breaks between 0.3 and 0.4, if you're using a mod that adds recipes for 0.3 it may not work and cause these issues with 0.4.

Since this is a hobby project and I'm just a volunteer, I'm not going to spend time troubleshooting from your modlist where the compatibility issue is. You need to isolate which mods/datapacks bundled with VE causes this issue on your end and then once it's isolated then I can take a look to see where the issue lies (on VE's end or the other author's end).

**Comment by border999** [comment]
I'm not willing to spend the time either, because if there are multiple then it's gonna take days of testing to find any number of them.
