### ISSUE TITLE
Recipe types with `minecraft:grass` causes undefined behaviour with the recipe

### ISSUE THREAD

**Issue by PositiveVibesVR** [MikeTheShadow/VoluminousEnergy#121]
Windows
Mod Version 1.20.4-0.5 alpha 1
Forge Version  49.0.51

![image_2024-05-31_003429743](https://github.com/MikeTheShadow/VoluminousEnergy/assets/87388997/7485c396-8032-4b41-809b-30a31c2d1784)

**Comment by Eelt** [comment]
This appears to be an issue with continuing to use `minecraft:grass` despite it being refactored upstream (by Mojang) to `minecraft:short_grass`. Any recipe type that has recipes using `minecraft:grass` causes undefined behaviour for all of those recipes (eg like for the Crusher here, but this also applies to the hydroponic incubator).

Will be fixed in the next hotfix

**Comment by Eelt** [comment]
Fixed in v1.20.4-0.5 Alpha 1a
