### ISSUE TITLE
When shift-clicking gives infinite XP

### ISSUE THREAD

**Issue by LonelySauce** [MikeTheShadow/VoluminousEnergy#26]
MC Version: 1.17.1
Forge Version: 37.0.84
Mod Version: VoluminousEnergy-1.17.1-0.2.1 Alpha 1.jar
https://youtu.be/k71QyR5HXV4
No crashes were involved, no logs shall be provided.

**Comment by LonelySauce** [comment]
Something else to note: Shift-clicking doesn't seem to work for any of the machines except for the Stirling generator

**Comment by Eelt** [comment]
Oh, yeah, the shift-clicking code is still broken even in Alpha 2. It needs to be rewritten for 1.17. This seems to be firing because it's assuming that the item is being extracted, but because it isn't (because the shift-click code is broken) you can shift-click again and again and again.

This is a great reminder for me that this needs to be fixed for all machines. It's just because the crusher is supposed to give XP on the removal of the item.

**Comment by Eelt** [comment]
This issue has been patched now and will be included in the next 1.17.1 release of Voluminous Energy.

I'll keep this issue open until the next release is available.
