### ISSUE TITLE
The Primitive Sterling Generator accepts power

### ISSUE THREAD

**Issue by ProsperCraft** [MikeTheShadow/VoluminousEnergy#27]
I would expect it would not sap power from the network and instead provide it.

**Comment by Eelt** [comment]
Hi there, 

I've conducted some testing using Mekanism's Universal Basic Cable with Voluminous Energy v1.16.5-0.2.2.0, and I cannot reproduce this issue with the Primitive Sterling Generator.

However, I would note, that when reloading the save, or possible unloading/reloading the chunk a little bit of power from my small test power network does seem to seep into the generator **but I feel that isn't the same issue described here** and is relatively minor (as it would be sent out immediately if a load was sent to the network and the generator doesn't continuously charge, just seems to charge a small bit on when loading the chunk).

 Could I ask you:
 1) What version of Minecraft and Voluminous Energy are you running?
 2) is this found on Single Player or Multiplayer (or reproducible on both if you know)?
 3) What other mods are you using and what item/block are you using to transport power from the Primitive Sterling Generator?

**Comment by ProsperCraft** [comment]
VoluminousEnergy-1.17.1-0.2 Alpha 3
Multiplayer on a dedicated server
Charging with advanced wireless charger it is also connected to a pipez pipe in pull mode.

**Comment by Eelt** [comment]
I've tested this with Forge 37.0.103 using a dedicated server, and wirelesschargers-1.0.1-mc1.17, and VoluminousEnergy-1.17.1-0.2 Alpha 3. I still couldn't reproduce this bug, the Primitive Stirling Generator did not charge, however, the advanced wireless charger block was charging from the Solar Panel

Here is the test setup:
![Setup](https://i.imgur.com/cl65yCq.png)

Here is the Solar Panel generating power (Charging because the wireless charger was now full):
![Solar Panel](https://i.imgur.com/bfFZZ1x.png)

And here is the Primitive Stirling Generator not charging despite being within the 7x7x7 range:
![Primitive Stirling Generator not charging](https://i.imgur.com/qBBzTMv.png)

And here is the proof that the wireless charger was full of FE:
![Wireless charger full](https://i.imgur.com/B4beeb4.png)

At this point, I don't know what you did differently to cause the Primitive Stirling Generator to charge, but at least with this setup, I cannot reproduce this issue. Additionally, I didn't use pipez, but I don't think that pipez would interact or would change the FE behaviour of the Primitive Stirling Generator or the Advanced Wireless Charger.

**Comment by MikeTheShadow** [comment]
Can't reproduce ourselves and 1.17.* is now unsupported

**Comment by Eelt** [comment]
Fixed in v1.18.2-0.3.0.3a
