### ISSUE TITLE
Rebalance raw ores

### ISSUE THREAD

**Issue by freopt** [MikeTheShadow/VoluminousEnergy#68]
**Is your feature request related to a problem? Please describe.**
Since 1.18 added raw ores, ore doubling of the raw ores themselves is pretty unbalanced, so other mods such as Immersive Enginnering and Tinkers Construct have changed doubling of raw ores to just a 33% bonus

**Describe the solution you'd like**
Change raw ore tags from forge:ores to forge:raw_ores as other mods have
make raw ores have a 33% bonus in the crusher (1 dust and 33% chance for another) as opposed to guaranteed 2

**Comment by Eelt** [comment]
Firstly the tag request I think is reasonable. I believe you're essentially asking to decouple the raw ores from the actual ores blocks tag-wise that Voluminous Energy did for 1.17 and when we backported raw ores (for materials in Voluminous Energy) to 1.16. For 0.3 we do require a newer Forge version that adds tags for `forge:raw_ores` so that's doable.

As for balancing, I don't really see why ore doubling is considered overpowered now compared to days past in 1.16 and 1.12. Are these mod developers expecting everyone to use Fortune III pickaxes or something when mining ores now? I'd say for some Voluminous Energy materials the ratios should maybe stay the same. Like for Rutile, or Eighzo (especially Eighzo), I would believe is hard/rare enough to justify ore doubling.

I quickly fired up ATM7, and I'm still seeing most machines doing Ore Doubling, albeit from the actual ores. Some mods do 1.3x for the raw ore to I guess encourage silk touch over fortune?

We are planning to do a balancing overhaul in the future update beyond 0.3 (0.4?) which we may consider rejigging the rates for raw ores, maybe even sooner. But I think un-tagging the raw ores as ores is something that'll be done sooner.

**Comment by freopt** [comment]
> Are these mod developers expecting everyone to use Fortune III pickaxes or something when mining ores now?

I mean when it triples your ore gain then why wouldn't you

> I'm still seeing most machines doing Ore Doubling, albeit from the actual ores

the actual ores are fine, it's the raw ores that make it op af
with fortune 3 (which is not that hard to obtain, especially with Apotheosis and other such mods, and apotheosis defaults fortune max level to 7) or tinkers' modifiers etc, you can get 6+ ingots from 1 ore, with minimal ore processing

**Comment by Eelt** [comment]
> with fortune 3 (which is not that hard to obtain, especially with Apotheosis and other such mods, and apotheosis defaults fortune max level to 7) or tinkers' modifiers etc, you can get 6+ ingots from 1 ore, with minimal ore processing

For the most part, this sounds like an Apotheosis/Tinker's balancing issue, not a Voluminous Energy balancing issue. I will still consider this idea but I shouldn't have to nerf my machines because Tinkers and magic mod developers can't get their balancing right. 

> I mean when it triples your ore gain then why wouldn't you

I suppose, but I would expect the average player to be able to obtain a crusher and be able to operate it before they get a Fortune III pickaxe, but I understand that not everyone may play in a way that prioritizes tech mods first. But I guess that's basically just Malcanis' law, there's no easy way to punish/nerf to prevent the OPness of fortune without punishing those who do not have fortune, and vice versa (Malcanis' law) make it easier in the early game without OPing for the mid-to-late game.

**Comment by Eelt** [comment]
Additionally, what should be done with the Raw Ore blocks one? 9 + 1/3 chance of 9 more?

Also for Copper, I guess the default guaranteed will still be Copper Carbonate Dust, with an additional chance of regular copper?

Any thoughts on this @freopt?

**Comment by freopt** [comment]
Raw ore blocks could be what you proposed or just guaranteed 12 dust (what IE did), mathematically they're the same

**Comment by Eelt** [comment]
Nerf will be included in the next build to be released for 1.18.2.
