### ISSUE TITLE
Error in currently selected datapacks preventing the world from loading

### ISSUE THREAD

**Issue by XxRexRaptorxX** [MikeTheShadow/VoluminousEnergy#99]
**Describe the bug**
Load the world and get the error in selected datapacks error

**To Reproduce**
Load the world

**latest.log:**
https://pastebin.com/VnVmZ96k

**Expected behavior**
Loading the world without error

**Desktop (please complete the following information):**
- OS (Windows, Mac, Linux) Windows 10
 - Mod Version [e.g. 22] 1.18.2 - 0.3.0.3b

**Comment by Eelt** [comment]
From the log file:
`Couldn't load tag hexerei:tallow as it is missing following references: hexerei:tallow_fluid (from VoluminousEnergy-1.18.2-0.3.0.3b.jar)`
Most likely an integration issue with Hexerei. For the time being, try removing Hexerei to see if that's the issue.

**Comment by XxRexRaptorxX** [comment]
Hexerei is not installed, i think thats the problem

**Comment by Eelt** [comment]
This issue is most likely fixed with v1.18.2-0.3.1.0 since integrations with 3rd party mods (except for JEI) have been removed from the base Voluminous Energy jar files, and the previous integrations are now going to be a separate mod.

Therefore, I believe this issue shouldn't occur with just the stock 0.3.1.0 jar file anymore. If so, maybe it's an issue with the recipe serializer if you're having trouble with custom recipes.
